allow to omit cluster creation
helm/kind-action pull request #50
Opened 2021-11-27 18:29 UTC by CezaryTarnowski-TomTom

In my pipeline, I'm creating a kind cluster with additional registry config as the following step, so during a build, I'm having two clusters created and it takes time. It would be nice to have the ability to just install kind without starting a cluster. That would save me around a minute on each build.

2022-02-10 12:09 UTC, JustynaMisiak-TomTom approved these changes

2022-04-13 07:35 UTC, cpanato requested changes
lgtm, thanks for this and sorry for taking too long

can you update your PR and fix the conflicts?

2022-04-21 07:44 UTC, CezaryTarnowski-TomTom commented
The PR is rebased.

2022-04-21 08:07 UTC, cpanato approved these changes

2022-04-21 08:07 UTC, merged